<?php
//conectando a base de dados...
//include "Connections/conecta_banco.php";
include "valida_cookie_admin.php";

//Pegando os valores digitados no formulario de cadastro de clientes e armazenando em arrays super globais
$ID_LAUDO 							= isset($_GET['ID_LAUDO']) ? $_GET['ID_LAUDO'] : '';
$LAUDO_USER							= isset($_GET['LAUDO_USER']) ? $_GET['LAUDO_USER'] : '';
$LAUDO_STATUS 						= isset($_GET['LAUDO_STATUS']) ? $_GET['LAUDO_STATUS'] : '';
//$LAUDO_TIPO 						= isset($_GET['LAUDO_TIPO']) ? $_GET['LAUDO_TIPO'] : '';
$LAUDO_TIPO = '1';

$LAUDO_LEADS 						= isset($_GET['ID_LEADS']) ? $_GET['ID_LEADS'] : '';
$LAUDO_JURIDICO 					= isset($_GET['ID_LEADS_JURIDICO']) ? $_GET['ID_LEADS_JURIDICO'] : '';

$LAUDO_ENVIO = '1';
$LAUDO_ENVIO_USER	= $ID_USER;
$LAUDO_ENVIO_DATA = date('Y/m/d');
$LAUDO_DATA = '0000/00/00';

$LAUDO_PROCESSUAL_DOC	= "";
$LAUDO_ENVIO_PROCESSUAL	= "";
$LAUDO_ENVIO_PROCESSUAL_USER = "";
$LAUDO_ENVIO_PROCESSUAL_DATA = '0000/00/00';

$LAUDO_N_CONTRATO 					= isset($_GET['LAUDO_N_CONTRATO']) ? $_GET['LAUDO_N_CONTRATO'] : '';
//$LAUDO_DATA_CONTRATO 				= isset($_GET['LAUDO_DATA_CONTRATO']) ? $_GET['LAUDO_DATA_CONTRATO'] : '';
$LAUDO_DATA_CONTRATO = '0000/00/00';

$LAUDO_PARCELA_CONTROVERSA 			= isset($_GET['LAUDO_PARCELA_CONTROVERSA']) ? $_GET['LAUDO_PARCELA_CONTROVERSA'] : '';
$LAUDO_PARCELA_INCONTROVERSA 		= isset($_GET['LAUDO_PARCELA_INCONTROVERSA']) ? $_GET['LAUDO_PARCELA_INCONTROVERSA'] : '';
$LAUDO_VALOR_VEICULO 				= isset($_GET['LAUDO_VALOR_VEICULO']) ? $_GET['LAUDO_VALOR_VEICULO'] : '';
$LAUDO_VALOR_ENTRADA 				= isset($_GET['LAUDO_VALOR_ENTRADA']) ? $_GET['LAUDO_VALOR_ENTRADA'] : '';
$LAUDO_IOF 							= isset($_GET['LAUDO_IOF']) ? $_GET['LAUDO_IOF'] : '';
$LAUDO_IOF_ADICIONAL 				= isset($_GET['LAUDO_IOF_ADICIONAL']) ? $_GET['LAUDO_IOF_ADICIONAL'] : '';
$LAUDO_VALOR_FINANCIADO 			= isset($_GET['LAUDO_VALOR_FINANCIADO']) ? $_GET['LAUDO_VALOR_FINANCIADO'] : '';
$LAUDO_TAXA_JUROS_CONTRATO 			= isset($_GET['LAUDO_TAXA_JUROS_CONTRATO']) ? $_GET['LAUDO_TAXA_JUROS_CONTRATO'] : '';
$LAUDO_TAXA_APLICADA_FINANCEIRA 	= isset($_GET['LAUDO_TAXA_APLICADA_FINANCEIRA']) ? $_GET['LAUDO_TAXA_APLICADA_FINANCEIRA'] : '';
$LAUDO_TARIFA_CADASTRO 				= isset($_GET['LAUDO_TARIFA_CADASTRO']) ? $_GET['LAUDO_TARIFA_CADASTRO'] : '';
$LAUDO_TARIFA_AVALIACAO 			= isset($_GET['LAUDO_TARIFA_AVALIACAO']) ? $_GET['LAUDO_TARIFA_AVALIACAO'] : '';
$LAUDO_REGISTRO_CONTRATO 			= isset($_GET['LAUDO_REGISTRO_CONTRATO']) ? $_GET['LAUDO_REGISTRO_CONTRATO'] : '';
$LAUDO_SEGURO 						= isset($_GET['LAUDO_SEGURO']) ? $_GET['LAUDO_SEGURO'] : '';
$LAUDO_TOTAL 						= isset($_GET['LAUDO_TOTAL']) ? $_GET['LAUDO_TOTAL'] : '';
$LAUDO_AMORTIZACAO 					= isset($_GET['LAUDO_AMORTIZACAO']) ? $_GET['LAUDO_AMORTIZACAO'] : '';
$LAUDO_RECALCULO 					= isset($_GET['LAUDO_RECALCULO']) ? $_GET['LAUDO_RECALCULO'] : '';
$LAUDO_PRESTACAO_CONTRATUAL 		= isset($_GET['LAUDO_PRESTACAO_CONTRATUAL']) ? $_GET['LAUDO_PRESTACAO_CONTRATUAL'] : '';
$LAUDO_N_PRESTACAO 					= isset($_GET['LAUDO_N_PRESTACAO']) ? $_GET['LAUDO_N_PRESTACAO'] : '';
$LAUDO_PRESTACAO_RECALCULADA 		= isset($_GET['LAUDO_PRESTACAO_RECALCULADA']) ? $_GET['LAUDO_PRESTACAO_RECALCULADA'] : '';
$LAUDO_DIFERENCA_PRESTACAO 			= isset($_GET['LAUDO_DIFERENCA_PRESTACAO']) ? $_GET['LAUDO_DIFERENCA_PRESTACAO'] : '';
$LAUDO_DIFERENCA_FINANCIAMENTO 		= isset($_GET['LAUDO_DIFERENCA_FINANCIAMENTO']) ? $_GET['LAUDO_DIFERENCA_FINANCIAMENTO'] : '';
$LAUDO_TARIFAS_DEVOLVER 			= isset($_GET['LAUDO_TARIFAS_DEVOLVER']) ? $_GET['LAUDO_TARIFAS_DEVOLVER'] : '';
$LAUDO_RECALCULO_DEVOLUCAO 			= isset($_GET['LAUDO_RECALCULO_DEVOLUCAO']) ? $_GET['LAUDO_RECALCULO_DEVOLUCAO'] : '';
$LAUDO_TOTAL_FINAL 					= isset($_GET['LAUDO_TOTAL_FINAL']) ? $_GET['LAUDO_TOTAL_FINAL'] : '';
$LAUDO_NOME_CONTABILIDADE			= isset($_GET['LAUDO_NOME_CONTABILIDADE']) ? $_GET['LAUDO_NOME_CONTABILIDADE'] : '';
$LAUDO_ARQUIVO						= isset($_GET['LAUDO_ARQUIVO']) ? $_GET['LAUDO_ARQUIVO'] : '';
$LAUDO_OBS 							= isset($_GET['LAUDO_OBS']) ? $_GET['LAUDO_OBS'] : '';



//$F_USER_REGISTRO = $_GET['F_USER_REGISTRO'];
$F_USER_REGISTRO = $USER_NOME;
$DATA_CADATRO = date("d/m/Y");
$HORA_CADASTRO = date("H:i");
$IP_CADASTRO = $_SERVER['REMOTE_ADDR'];

//$F_USER_ULT_ALTERACAO = $_GET['F_USER_REGISTRO'];
//$DATA_ULT_ALTERACAO = date("d/m/Y");
//$HORA_ULT_ALTERACAO = date("H:i");
//$IP_ULT_ALTERACAO = $_SERVER['REMOTE_ADDR'];

$F_USER_ULT_ALTERACAO = '';
$DATA_ULT_ALTERACAO = '';
$HORA_ULT_ALTERACAO = '';
$IP_ULT_ALTERACAO = '';

//inserindo informoçoes na base...
mysqli_query ($conexao,"INSERT INTO tb_laudo (ID_LAUDO, LAUDO_USER, LAUDO_STATUS, LAUDO_TIPO, LAUDO_LEADS, LAUDO_JURIDICO, LAUDO_ENVIO, LAUDO_ENVIO_USER, LAUDO_ENVIO_DATA, LAUDO_PROCESSUAL_DOC, LAUDO_ENVIO_PROCESSUAL, LAUDO_ENVIO_PROCESSUAL_USER, LAUDO_ENVIO_PROCESSUAL_DATA, LAUDO_DATA, LAUDO_N_CONTRATO, LAUDO_DATA_CONTRATO, LAUDO_PARCELA_CONTROVERSA, LAUDO_PARCELA_INCONTROVERSA, LAUDO_VALOR_VEICULO, LAUDO_VALOR_ENTRADA, LAUDO_IOF, LAUDO_IOF_ADICIONAL, LAUDO_VALOR_FINANCIADO, LAUDO_TAXA_JUROS_CONTRATO, LAUDO_TAXA_APLICADA_FINANCEIRA, LAUDO_TARIFA_CADASTRO, LAUDO_TARIFA_AVALIACAO, LAUDO_REGISTRO_CONTRATO, LAUDO_SEGURO, LAUDO_TOTAL, LAUDO_AMORTIZACAO, LAUDO_RECALCULO, LAUDO_PRESTACAO_CONTRATUAL, LAUDO_N_PRESTACAO, LAUDO_PRESTACAO_RECALCULADA, LAUDO_DIFERENCA_PRESTACAO, LAUDO_DIFERENCA_FINANCIAMENTO, LAUDO_TARIFAS_DEVOLVER, LAUDO_RECALCULO_DEVOLUCAO, LAUDO_TOTAL_FINAL, LAUDO_NOME_CONTABILIDADE, LAUDO_ARQUIVO, LAUDO_OBS, F_USER_REGISTRO, DATA_CADATRO, HORA_CADASTRO, IP_CADASTRO, F_USER_ULT_ALTERACAO, DATA_ULT_ALTERACAO, HORA_ULT_ALTERACAO, IP_ULT_ALTERACAO) VALUES (null, '$LAUDO_USER', '$LAUDO_STATUS', '$LAUDO_TIPO', '$LAUDO_LEADS', '$LAUDO_JURIDICO', '$LAUDO_ENVIO', '$LAUDO_ENVIO_USER', '$LAUDO_ENVIO_DATA', '$LAUDO_PROCESSUAL_DOC', '$LAUDO_ENVIO_PROCESSUAL', '$LAUDO_ENVIO_PROCESSUAL_USER', '$LAUDO_ENVIO_PROCESSUAL_DATA', '$LAUDO_DATA', '$LAUDO_N_CONTRATO', '$LAUDO_DATA_CONTRATO', '$LAUDO_PARCELA_CONTROVERSA', '$LAUDO_PARCELA_INCONTROVERSA', '$LAUDO_VALOR_VEICULO', '$LAUDO_VALOR_ENTRADA', '$LAUDO_IOF', '$LAUDO_IOF_ADICIONAL', '$LAUDO_VALOR_FINANCIADO', '$LAUDO_TAXA_JUROS_CONTRATO', '$LAUDO_TAXA_APLICADA_FINANCEIRA', '$LAUDO_TARIFA_CADASTRO', '$LAUDO_TARIFA_AVALIACAO', '$LAUDO_REGISTRO_CONTRATO', '$LAUDO_SEGURO', '$LAUDO_TOTAL', '$LAUDO_AMORTIZACAO', '$LAUDO_RECALCULO', '$LAUDO_PRESTACAO_CONTRATUAL', '$LAUDO_N_PRESTACAO', '$LAUDO_PRESTACAO_RECALCULADA', '$LAUDO_DIFERENCA_PRESTACAO', '$LAUDO_DIFERENCA_FINANCIAMENTO', '$LAUDO_TARIFAS_DEVOLVER', '$LAUDO_RECALCULO_DEVOLUCAO', '$LAUDO_TOTAL_FINAL', '$LAUDO_ARQUIVO', '$LAUDO_OBS', '$LAUDO_OBS', '$F_USER_REGISTRO', '$DATA_CADATRO', '$HORA_CADASTRO', '$IP_CADASTRO', '$F_USER_ULT_ALTERACAO', '$DATA_ULT_ALTERACAO', '$HORA_ULT_ALTERACAO', '$IP_ULT_ALTERACAO')");
if (mysqli_affected_rows ($conexao)>0);




/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/*	
$OP_ADM_STATUS 				= '1';
//$OP_ADM_DATA_ENVIO_JUR 			= isset($_GET['OP_ADM_DATA_ENVIO_JUR']) ? $_GET['OP_ADM_DATA_ENVIO_JUR'] : '';
$OP_ADM_DATA_ENVIO_JUR  	= date('Y/m/d');
$OP_ADM_USER_ENVIO_JUR		= $ID_USER;
$OP_ADM_ENVIA_JUR 			= '1';

//inserindo informoçoes na base...
$sql = "UPDATE tb_leads_op_adm SET
OP_ADM_STATUS='$OP_ADM_STATUS',
OP_ADM_DATA_ENVIO_JUR='$OP_ADM_DATA_ENVIO_JUR',
OP_ADM_USER_ENVIO_JUR='$OP_ADM_USER_ENVIO_JUR',
OP_ADM_ENVIA_JUR='$OP_ADM_ENVIA_JUR',
F_USER_ULT_ALTERACAO='$F_USER_ULT_ALTERACAO',
DATA_ULT_ALTERACAO='$DATA_ULT_ALTERACAO', 
HORA_ULT_ALTERACAO='$HORA_ULT_ALTERACAO', 
IP_ULT_ALTERACAO='$IP_ULT_ALTERACAO' 
WHERE OP_ADM_LEADS='$LEADS_JURIDICO_LEADS';";
$res = mysqli_query ($conexao, $sql);
*/

?>
<script language="javascript">
<!-- Caso a condição acima seja verdadeira o script abaiso será execultado-->
alert ('PASTA enviado com sucesso!');
location.href = 'principal-juridico-laudo-fechado.php';
S</script>