<?php
//conectando a base de dados...
//include "Connections/conecta_banco.php";
include "valida_cookie_admin.php";

//Pegando os valores digitados no formulario de cadastro de clientes e armazenando em arrays super globais
$ID_LEADS_JURIDICO 					= isset($_GET['ID_LEADS_JURIDICO']) ? $_GET['ID_LEADS_JURIDICO'] : '';
$LEADS_JURIDICO_USER				= isset($_GET['LEADS_JURIDICO_USER']) ? $_GET['LEADS_JURIDICO_USER'] : '';
$LEADS_JURIDICO_STATUS 				= isset($_GET['LEADS_JURIDICO_STATUS']) ? $_GET['LEADS_JURIDICO_STATUS'] : '';
//$LEADS_JURIDICO_LEADS 				= isset($_GET['LEADS_JURIDICO_LEADS']) ? $_GET['LEADS_JURIDICO_LEADS'] : '';
$LEADS_JURIDICO_LEADS 				= isset($_GET['ID_LEADS']) ? $_GET['ID_LEADS'] : '';

$LEADS_JURIDICO_ENVIO_USER			= $ID_USER;
$LEADS_JURIDICO_ENVIO_DATA = date('Y/m/d');

$LEADS_JURIDICO_DISTRIBUIDO_USER	= isset($_GET['LEADS_JURIDICO_DISTRIBUIDO_USER']) ? $_GET['LEADS_JURIDICO_DISTRIBUIDO_USER'] : '';
$LEADS_JURIDICO_DISTRIBUIDO			= isset($_GET['LEADS_JURIDICO_DISTRIBUIDO']) ? $_GET['LEADS_JURIDICO_DISTRIBUIDO'] : '';
$LEADS_JURIDICO_DISTRIBUIDO_DATA = '0000/00/00';






///////////////////////////////////////////////////////
/////////////	SELECIONA SE O LEADS JÁ FOI ENVIADO	//
$sql_env_leads = mysqli_query($conexao,"select * from tb_leads_op_adm WHERE OP_ADM_LEADS = '$LEADS_JURIDICO_LEADS' ");
$val_env_leads = mysqli_fetch_object($sql_env_leads);  
///////////////////////////////////////////////////////
//$ID_OP_ADM 			= isset($val_env_leads->ID_OP_ADM) ? $val_env_leads->ID_OP_ADM : '';
$OP_ADM_FATURAMENTO 			= isset($val_env_leads->OP_ADM_FATURAMENTO) ? $val_env_leads->OP_ADM_FATURAMENTO : '';

if($OP_ADM_FATURAMENTO > '')
$LEADS_JURIDICO_FATURAMENTO = $OP_ADM_FATURAMENTO;
else
$LEADS_JURIDICO_FATURAMENTO 		= isset($_GET['LEADS_JURIDICO_FATURAMENTO']) ? $_GET['LEADS_JURIDICO_FATURAMENTO'] : '';

$LEADS_JURIDICO_SENHA_GOV = '';
$LEADS_JURIDICO_STATUS_DOC = '';
$LEADS_JURIDICO_CONSUMINOR_USER = '';
$LEADS_JURIDICO_CONSUMIDOR_ENVIADO = '';
$LEADS_JURIDICO_CONSUMIDOR_DATA = '0000/00/00';
$LEADS_JURIDICO_CONSUMIDOR_RECEBIDO = '';
$LEADS_JURIDICO_CONSUMIDOR_DATA_RECEBIDO = '0000/00/00';

$LEADS_JURIDICO_OBS 				= isset($_GET['LEADS_JURIDICO_OBS']) ? $_GET['LEADS_JURIDICO_OBS'] : '';

//$F_USER_REGISTRO = $_GET['F_USER_REGISTRO'];
$F_USER_REGISTRO = $USER_NOME;
$DATA_CADATRO = date("d/m/Y");
$HORA_CADASTRO = date("H:i");
$IP_CADASTRO = $_SERVER['REMOTE_ADDR'];

//$F_USER_ULT_ALTERACAO = $_GET['F_USER_REGISTRO'];
//$DATA_ULT_ALTERACAO = date("d/m/Y");
//$HORA_ULT_ALTERACAO = date("H:i");
//$IP_ULT_ALTERACAO = $_SERVER['REMOTE_ADDR'];

$F_USER_ULT_ALTERACAO = '';
$DATA_ULT_ALTERACAO = '';
$HORA_ULT_ALTERACAO = '';
$IP_ULT_ALTERACAO = '';

//inserindo informoçoes na base...
mysqli_query ($conexao,"INSERT INTO tb_leads_juridico (ID_LEADS_JURIDICO, LEADS_JURIDICO_USER, LEADS_JURIDICO_STATUS, LEADS_JURIDICO_LEADS, LEADS_JURIDICO_ENVIO_USER, LEADS_JURIDICO_ENVIO_DATA, LEADS_JURIDICO_DISTRIBUIDO_USER, LEADS_JURIDICO_DISTRIBUIDO, LEADS_JURIDICO_DISTRIBUIDO_DATA, LEADS_JURIDICO_FATURAMENTO, LEADS_JURIDICO_SENHA_GOV, LEADS_JURIDICO_STATUS_DOC, LEADS_JURIDICO_CONSUMIDOR_USER, LEADS_JURIDICO_CONSUMIDOR_ENVIADO, LEADS_JURIDICO_CONSUMIDOR_DATA, LEADS_JURIDICO_CONSUMIDOR_RECEBIDO, LEADS_JURIDICO_CONSUMIDOR_DATA_RECEBIDO, LEADS_JURIDICO_OBS, F_USER_REGISTRO, DATA_CADATRO, HORA_CADASTRO, IP_CADASTRO, F_USER_ULT_ALTERACAO, DATA_ULT_ALTERACAO, HORA_ULT_ALTERACAO, IP_ULT_ALTERACAO) VALUES (null, '$LEADS_JURIDICO_USER', '$LEADS_JURIDICO_STATUS', '$LEADS_JURIDICO_LEADS', '$LEADS_JURIDICO_ENVIO_USER', '$LEADS_JURIDICO_ENVIO_DATA', '$LEADS_JURIDICO_DISTRIBUIDO_USER', '$LEADS_JURIDICO_DISTRIBUIDO', '$LEADS_JURIDICO_DISTRIBUIDO_DATA', '$LEADS_JURIDICO_FATURAMENTO', '$LEADS_JURIDICO_SENHA_GOV', '$LEADS_JURIDICO_STATUS_DOC', '$LEADS_JURIDICO_CONSUMIDOR_USER', '$LEADS_JURIDICO_CONSUMIDOR_ENVIADO', '$LEADS_JURIDICO_CONSUMIDOR_DATA', '$LEADS_JURIDICO_CONSUMIDOR_RECEBIDO', '$LEADS_JURIDICO_CONSUMIDOR_DATA_RECEBIDO', '$LEADS_JURIDICO_OBS', '$F_USER_REGISTRO', '$DATA_CADATRO', '$HORA_CADASTRO', '$IP_CADASTRO', '$F_USER_ULT_ALTERACAO', '$DATA_ULT_ALTERACAO', '$HORA_ULT_ALTERACAO', '$IP_ULT_ALTERACAO')");
//if (mysqli_affected_rows ($conexao)>0);




/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	
$OP_ADM_STATUS 				= '1';
//$OP_ADM_DATA_ENVIO_JUR 			= isset($_GET['OP_ADM_DATA_ENVIO_JUR']) ? $_GET['OP_ADM_DATA_ENVIO_JUR'] : '';
$OP_ADM_DATA_ENVIO_JUR  	= date('Y/m/d');
$OP_ADM_USER_ENVIO_JUR		= $ID_USER;
$OP_ADM_ENVIA_JUR 			= '1';

//inserindo informoçoes na base...
$sql = "UPDATE tb_leads_op_adm SET
OP_ADM_STATUS='$OP_ADM_STATUS',
OP_ADM_DATA_ENVIO_JUR='$OP_ADM_DATA_ENVIO_JUR',
OP_ADM_USER_ENVIO_JUR='$OP_ADM_USER_ENVIO_JUR',
OP_ADM_ENVIA_JUR='$OP_ADM_ENVIA_JUR',
F_USER_ULT_ALTERACAO='$F_USER_ULT_ALTERACAO',
DATA_ULT_ALTERACAO='$DATA_ULT_ALTERACAO', 
HORA_ULT_ALTERACAO='$HORA_ULT_ALTERACAO', 
IP_ULT_ALTERACAO='$IP_ULT_ALTERACAO' 
WHERE OP_ADM_LEADS='$LEADS_JURIDICO_LEADS';";
$res = mysqli_query ($conexao, $sql);


?>
<script language="javascript">
<!-- Caso a condição acima seja verdadeira o script abaiso será execultado-->
alert ('LEADS enviado com sucesso!');
location.href = 'principal-leads-op-adm.php';
</script>