<?php
//conectando a base de dados...
include "Connections/conecta_banco.php";


$ID_LEADS 			= isset($_POST['FICHA_INTER_LEADS']) ? $_POST['FICHA_INTER_LEADS'] : '';
//$ID_FICHA_INTER	= isset($_POST['ID_FICHA_INTER']) ? $_POST['ID_FICHA_INTER'] : '';

$CLIENTE_CPF 			= isset($_POST['CLIENTE_CPF']) ? $_POST['CLIENTE_CPF'] : '';
$CLIENTE_CNPJ 			= isset($_POST['CLIENTE_CNPJ']) ? $_POST['CLIENTE_CNPJ'] : '';

$val_cliente = mysqli_query($conexao,"select * from tb_clientes WHERE CLIENTE_CPF = '$CLIENTE_CPF' ");
$val_cliente = mysqli_fetch_object($val_cliente);  
$val_id_cliente = isset($val_cliente->ID_CLIENTE) ? $val_cliente->ID_CLIENTE : '';

if($val_id_cliente > '')	{
$val_id_cliente = isset($val_cliente->ID_CLIENTE) ? $val_cliente->ID_CLIENTE : '';

$CLIENTE_STATUS 		= '1';
$CLIENTE_TIPO 			= isset($_POST['CLIENTE_TIPO']) ? $_POST['CLIENTE_TIPO'] : '';
$CLIENTE_NOME 			= isset($_POST['CLIENTE_NOME']) ? $_POST['CLIENTE_NOME'] : '';
$CLIENTE_RESPONSAVEL 	= isset($_POST['CLIENTE_RESPONSAVEL']) ? $_POST['CLIENTE_RESPONSAVEL'] : '';
$CLIENTE_CNPJ 			= isset($_POST['CLIENTE_CNPJ']) ? $_POST['CLIENTE_CNPJ'] : '';
$CLIENTE_CPF 			= isset($_POST['CLIENTE_CPF']) ? $_POST['CLIENTE_CPF'] : '';
$CLIENTE_RG 			= isset($_POST['CLIENTE_RG']) ? $_POST['CLIENTE_RG'] : '';
$CLIENTE_DATA_NASC		= isset($_POST['CLIENTE_DATA_NASC']) ? $_POST['CLIENTE_DATA_NASC'] : '';
$CLIENTE_TELEFONE_1 	= isset($_POST['CLIENTE_TELEFONE_1']) ? $_POST['CLIENTE_TELEFONE_1'] : '';
$CLIENTE_TELEFONE_2 	= isset($_POST['CLIENTE_TELEFONE_2']) ? $_POST['CLIENTE_TELEFONE_2'] : '';
$CLIENTE_ESTADO_CIVIL	= isset($_POST['CLIENTE_ESTADO_CIVIL']) ? $_POST['CLIENTE_ESTADO_CIVIL'] : '';
$CLIENTE_PROFISSAO		= isset($_POST['CLIENTE_PROFISSAO']) ? $_POST['CLIENTE_PROFISSAO'] : '';
$CLIENTE_EMAIL 			= isset($_POST['CLIENTE_EMAIL']) ? $_POST['CLIENTE_EMAIL'] : '';
$CLIENTE_ENDERECO 		= isset($_POST['CLIENTE_ENDERECO']) ? $_POST['CLIENTE_ENDERECO'] : '';
$CLIENTE_N 				= isset($_POST['CLIENTE_N']) ? $_POST['CLIENTE_N'] : '';
$CLIENTE_COMPLEMENTO	= isset($_POST['CLIENTE_COMPLEMENTO']) ? $_POST['CLIENTE_COMPLEMENTO'] : '';
$CLIENTE_BAIRRO 		= isset($_POST['CLIENTE_BAIRRO']) ? $_POST['CLIENTE_BAIRRO'] : '';
$CLIENTE_CIDADE 		= isset($_POST['CLIENTE_CIDADE']) ? $_POST['CLIENTE_CIDADE'] : '';
$CLIENTE_UF 			= isset($_POST['CLIENTE_UF']) ? $_POST['CLIENTE_UF'] : '';
$CLIENTE_CEP 			= isset($_POST['CLIENTE_CEP']) ? $_POST['CLIENTE_CEP'] : '';
$CLIENTE_OBS 			= isset($_POST['CLIENTE_OBS']) ? $_POST['CLIENTE_OBS'] : '';

$F_USER_ULT_ALTERACAO = $_POST['F_USER_REGISTRO'];
$DATA_ULT_ALTERACAO = date("d/m/Y");
$HORA_ULT_ALTERACAO = date("H:i");
$IP_ULT_ALTERACAO = $_SERVER['REMOTE_ADDR'];


//inserindo informoçoes na base...
$sql = "UPDATE tb_clientes SET
CLIENTE_NOME='$CLIENTE_NOME',
CLIENTE_CNPJ='$CLIENTE_CNPJ',
CLIENTE_CPF='$CLIENTE_CPF',
CLIENTE_RG='$CLIENTE_RG',
CLIENTE_DATA_NASC='$CLIENTE_DATA_NASC',
CLIENTE_TELEFONE_1='$CLIENTE_TELEFONE_1',
CLIENTE_TELEFONE_2='$CLIENTE_TELEFONE_2',
CLIENTE_ESTADO_CIVIL='$CLIENTE_ESTADO_CIVIL',
CLIENTE_PROFISSAO='$CLIENTE_PROFISSAO',
CLIENTE_EMAIL='$CLIENTE_EMAIL',
CLIENTE_ENDERECO='$CLIENTE_ENDERECO',
CLIENTE_N='$CLIENTE_N',
CLIENTE_COMPLEMENTO='$CLIENTE_COMPLEMENTO',
CLIENTE_BAIRRO='$CLIENTE_BAIRRO',
CLIENTE_CIDADE='$CLIENTE_CIDADE',
CLIENTE_UF='$CLIENTE_UF',
CLIENTE_CEP='$CLIENTE_CEP',
CLIENTE_OBS='$CLIENTE_OBS',
F_USER_ULT_ALTERACAO='$F_USER_ULT_ALTERACAO',
DATA_ULT_ALTERACAO='$DATA_ULT_ALTERACAO', 
HORA_ULT_ALTERACAO='$HORA_ULT_ALTERACAO', 
IP_ULT_ALTERACAO='$IP_ULT_ALTERACAO' 
WHERE ID_CLIENTE='$val_id_cliente';";
$res = mysqli_query ($conexao, $sql);

?>
<script language="javascript">
<!-- Caso a condição acima seja verdadeira o script abaiso será execultado-->
//alert ('CPF/CNPJ - já Cadastrado!');
//location.href = 'operador-ficha-intermediacao.php?ID_LEADS=<?php echo $ID_LEADS; ?>	';
</script>
<?php
}	elseif($val_id_cliente == '')	{
//Pegando os valores digitados no formulario de cadastro de clientes e armazenando em arrays super globais
$ID_CLIENTE 			= isset($_POST['ID_CLIENTE']) ? $_POST['ID_CLIENTE'] : '';
//$CLIENTE_USER 			= isset($_POST['CLIENTE_USER']) ? $_POST['CLIENTE_USER'] : '';
$CLIENTE_USER 			= isset($_POST['FICHA_INTER_USER']) ? $_POST['FICHA_INTER_USER'] : '';
//$CLIENTE_STATUS 		= isset($_POST['CLIENTE_STATUS']) ? $_POST['CLIENTE_STATUS'] : '';
$CLIENTE_STATUS 		= '1';
$CLIENTE_TIPO 			= isset($_POST['CLIENTE_TIPO']) ? $_POST['CLIENTE_TIPO'] : '';
$CLIENTE_NOME 			= isset($_POST['CLIENTE_NOME']) ? $_POST['CLIENTE_NOME'] : '';
$CLIENTE_RESPONSAVEL 	= isset($_POST['CLIENTE_RESPONSAVEL']) ? $_POST['CLIENTE_RESPONSAVEL'] : '';
$CLIENTE_CNPJ 			= isset($_POST['CLIENTE_CNPJ']) ? $_POST['CLIENTE_CNPJ'] : '';
$CLIENTE_CPF 			= isset($_POST['CLIENTE_CPF']) ? $_POST['CLIENTE_CPF'] : '';
$CLIENTE_RG 			= isset($_POST['CLIENTE_RG']) ? $_POST['CLIENTE_RG'] : '';
$CLIENTE_DATA_NASC		= isset($_POST['CLIENTE_DATA_NASC']) ? $_POST['CLIENTE_DATA_NASC'] : '';
$CLIENTE_TELEFONE_1 	= isset($_POST['CLIENTE_TELEFONE_1']) ? $_POST['CLIENTE_TELEFONE_1'] : '';
$CLIENTE_TELEFONE_2 	= isset($_POST['CLIENTE_TELEFONE_2']) ? $_POST['CLIENTE_TELEFONE_2'] : '';
$CLIENTE_ESTADO_CIVIL	= isset($_POST['CLIENTE_ESTADO_CIVIL']) ? $_POST['CLIENTE_ESTADO_CIVIL'] : '';
$CLIENTE_PROFISSAO		= isset($_POST['CLIENTE_PROFISSAO']) ? $_POST['CLIENTE_PROFISSAO'] : '';
$CLIENTE_EMAIL 			= isset($_POST['CLIENTE_EMAIL']) ? $_POST['CLIENTE_EMAIL'] : '';
$CLIENTE_ENDERECO 		= isset($_POST['CLIENTE_ENDERECO']) ? $_POST['CLIENTE_ENDERECO'] : '';
$CLIENTE_N 				= isset($_POST['CLIENTE_N']) ? $_POST['CLIENTE_N'] : '';
$CLIENTE_COMPLEMENTO	= isset($_POST['CLIENTE_COMPLEMENTO']) ? $_POST['CLIENTE_COMPLEMENTO'] : '';
$CLIENTE_BAIRRO 		= isset($_POST['CLIENTE_BAIRRO']) ? $_POST['CLIENTE_BAIRRO'] : '';
$CLIENTE_CIDADE 		= isset($_POST['CLIENTE_CIDADE']) ? $_POST['CLIENTE_CIDADE'] : '';
$CLIENTE_UF 			= isset($_POST['CLIENTE_UF']) ? $_POST['CLIENTE_UF'] : '';
$CLIENTE_CEP 			= isset($_POST['CLIENTE_CEP']) ? $_POST['CLIENTE_CEP'] : '';
$CLIENTE_OBS 			= isset($_POST['CLIENTE_OBS']) ? $_POST['CLIENTE_OBS'] : '';

$F_USER_REGISTRO = $_POST['F_USER_REGISTRO'];
$DATA_CADATRO = date("d/m/Y");
$HORA_CADASTRO = date("H:i");
$IP_CADASTRO = $_SERVER['REMOTE_ADDR'];

$F_USER_ULT_ALTERACAO = '';
$DATA_ULT_ALTERACAO = '';
$HORA_ULT_ALTERACAO = '';
$IP_ULT_ALTERACAO = '';

//inserindo informoçoes na base...
mysqli_query ($conexao,"INSERT INTO tb_clientes (ID_CLIENTE, CLIENTE_USER, CLIENTE_STATUS, CLIENTE_TIPO, CLIENTE_NOME, CLIENTE_RESPONSAVEL, CLIENTE_CNPJ, CLIENTE_CPF, CLIENTE_RG, CLIENTE_DATA_NASC, CLIENTE_TELEFONE_1, CLIENTE_TELEFONE_2, CLIENTE_ESTADO_CIVIL, CLIENTE_PROFISSAO, CLIENTE_EMAIL, CLIENTE_ENDERECO, CLIENTE_N, CLIENTE_COMPLEMENTO, CLIENTE_BAIRRO, CLIENTE_CIDADE, CLIENTE_UF, CLIENTE_CEP, CLIENTE_OBS, F_USER_REGISTRO, DATA_CADATRO, HORA_CADASTRO, IP_CADASTRO, F_USER_ULT_ALTERACAO, DATA_ULT_ALTERACAO, HORA_ULT_ALTERACAO, IP_ULT_ALTERACAO) VALUES (null, '$CLIENTE_USER', '$CLIENTE_STATUS', '$CLIENTE_TIPO', '$CLIENTE_NOME', '$CLIENTE_RESPONSAVEL', '$CLIENTE_CNPJ', '$CLIENTE_CPF', '$CLIENTE_RG', '$CLIENTE_DATA_NASC', '$CLIENTE_TELEFONE_1', '$CLIENTE_TELEFONE_2', '$CLIENTE_ESTADO_CIVIL', '$CLIENTE_PROFISSAO', '$CLIENTE_EMAIL', '$CLIENTE_ENDERECO', '$CLIENTE_N', '$CLIENTE_COMPLEMENTO', '$CLIENTE_BAIRRO', '$CLIENTE_CIDADE', '$CLIENTE_UF', '$CLIENTE_CEP', '$CLIENTE_OBS', '$F_USER_REGISTRO', '$DATA_CADATRO', '$HORA_CADASTRO', '$IP_CADASTRO', '$F_USER_ULT_ALTERACAO', '$DATA_ULT_ALTERACAO', '$HORA_ULT_ALTERACAO', '$IP_ULT_ALTERACAO')");
if (mysqli_affected_rows ($conexao)>0);
$val_id_cliente = mysqli_insert_id($conexao);
}



$ID_FICHA_INTER 			= isset($_POST['ID_FICHA_INTER']) ? $_POST['ID_FICHA_INTER'] : '';
$FICHA_INTER_USER 			= isset($_POST['FICHA_INTER_USER']) ? $_POST['FICHA_INTER_USER'] : '';
//$FICHA_INTER_STATUS 		= isset($_POST['FICHA_INTER_STATUS']) ? $_POST['FICHA_INTER_STATUS'] : '';
$FICHA_INTER_STATUS 		= '1';
$FICHA_INTER_TIPO 			= isset($_POST['FICHA_INTER_TIPO']) ? $_POST['FICHA_INTER_TIPO'] : '';
$FICHA_INTER_LEADS 			= isset($_POST['FICHA_INTER_LEADS']) ? $_POST['FICHA_INTER_LEADS'] : '';

$FICHA_INTER_DATA 			= isset($_POST['FICHA_INTER_DATA']) ? $_POST['FICHA_INTER_DATA'] : '';
if($FICHA_INTER_DATA > '')	{
$FICHA_INTER_DATA_DIA = substr($FICHA_INTER_DATA, 0, 2);
$FICHA_INTER_DATA_MES = substr($FICHA_INTER_DATA, 3, 2);
$FICHA_INTER_DATA_ANO = substr($FICHA_INTER_DATA, 6, 4);
$FICHA_INTER_DATA = $FICHA_INTER_DATA_ANO.'/'.$FICHA_INTER_DATA_MES.'/'.$FICHA_INTER_DATA_DIA;
} else	{
	$FICHA_INTER_DATA = '0000/00/00';
}

//$FICHA_INTER_CLIENTE		= isset($_POST['FICHA_INTER_CLIENTE']) ? $_POST['FICHA_INTER_CLIENTE'] : '';
$FICHA_INTER_CLIENTE		= $val_id_cliente;

$FICHA_INTER_ENVIO 			= isset($_POST['FICHA_INTER_ENVIO']) ? $_POST['FICHA_INTER_ENVIO'] : '';
$FICHA_INTER_ENVIO_HORARIO	= isset($_POST['FICHA_INTER_ENVIO_HORARIO']) ? $_POST['FICHA_INTER_ENVIO_HORARIO'] : '';
$FICHA_INTER_ENVIO_ENDERECO = isset($_POST['FICHA_INTER_ENVIO_ENDERECO']) ? $_POST['FICHA_INTER_ENVIO_ENDERECO'] : '';
$FICHA_INTER_ENVIO_N		= isset($_POST['FICHA_INTER_ENVIO_N']) ? $_POST['FICHA_INTER_ENVIO_N'] : '';
$FICHA_INTER_ENVIO_COMP		= isset($_POST['FICHA_INTER_ENVIO_COMP']) ? $_POST['FICHA_INTER_ENVIO_COMP'] : '';
$FICHA_INTER_ENVIO_CEP		= isset($_POST['FICHA_INTER_ENVIO_CEP']) ? $_POST['FICHA_INTER_ENVIO_CEP'] : '';
$FICHA_INTER_ENVIO_BAIRRO	= isset($_POST['FICHA_INTER_ENVIO_BAIRRO']) ? $_POST['FICHA_INTER_ENVIO_BAIRRO'] : '';
$FICHA_INTER_ENVIO_CIDADE	= isset($_POST['FICHA_INTER_ENVIO_CIDADE']) ? $_POST['FICHA_INTER_ENVIO_CIDADE'] : '';

$FICHA_INTER_BUSCA_APREENSAO	= isset($_POST['FICHA_INTER_BUSCA_APREENSAO']) ? $_POST['FICHA_INTER_BUSCA_APREENSAO'] : '';

$FICHA_INTER_BANCO			= isset($_POST['FICHA_INTER_BANCO']) ? $_POST['FICHA_INTER_BANCO'] : '';
$FICHA_INTER_VEICULO		= isset($_POST['FICHA_INTER_VEICULO']) ? $_POST['FICHA_INTER_VEICULO'] : '';
$FICHA_INTER_VALOR_FIN		= isset($_POST['FICHA_INTER_VALOR_FIN']) ? $_POST['FICHA_INTER_VALOR_FIN'] : '';
$FICHA_INTER_VALOR_PARC		= isset($_POST['FICHA_INTER_VALOR_PARC']) ? $_POST['FICHA_INTER_VALOR_PARC'] : '';
$FICHA_INTER_PAGA 			= isset($_POST['FICHA_INTER_PAGA']) ? $_POST['FICHA_INTER_PAGA'] : '';
$FICHA_INTER_ATRASO			= isset($_POST['FICHA_INTER_ATRASO']) ? $_POST['FICHA_INTER_ATRASO'] : '';
$FICHA_INTER_OBS 			= isset($_POST['FICHA_INTER_OBS']) ? $_POST['FICHA_INTER_OBS'] : '';

$F_USER_REGISTRO = $_POST['F_USER_REGISTRO'];
$DATA_CADATRO = date("d/m/Y");
$HORA_CADASTRO = date("H:i");
$IP_CADASTRO = $_SERVER['REMOTE_ADDR'];

$F_USER_ULT_ALTERACAO = '';
$DATA_ULT_ALTERACAO = '';
$HORA_ULT_ALTERACAO = '';
$IP_ULT_ALTERACAO = '';


//inserindo informoçoes na base...
//mysqli_query ($conexao,"INSERT INTO tb_ficha_intermediacao (ID_FICHA_INTER, FICHA_INTER_USER, FICHA_INTER_STATUS, FICHA_INTER_TIPO, FICHA_INTER_LEADS, FICHA_INTER_DATA, FICHA_INTER_CLIENTE, FICHA_INTER_ENVIO, FICHA_INTER_ENVIO_HORARIO, FICHA_INTER_ENVIO_ENDERECO, FICHA_INTER_ENVIO_N, FICHA_INTER_ENVIO_COMP, FICHA_INTER_ENVIO_CEP, FICHA_INTER_ENVIO_BAIRRO, FICHA_INTER_ENVIO_CIDADE, FICHA_INTER_BANCO, FICHA_INTER_VEICULO, FICHA_INTER_VALOR_FIN, FICHA_INTER_VALOR_PARC, FICHA_INTER_PAGA, FICHA_INTER_ATRASO, FICHA_INTER_OBS, F_USER_REGISTRO, DATA_CADATRO, HORA_CADASTRO, IP_CADASTRO, F_USER_ULT_ALTERACAO, DATA_ULT_ALTERACAO, HORA_ULT_ALTERACAO, IP_ULT_ALTERACAO) VALUES (null, '$FICHA_INTER_USER', '$FICHA_INTER_STATUS', '$FICHA_INTER_TIPO', '$FICHA_INTER_LEADS', '$FICHA_INTER_DATA', '$FICHA_INTER_CLIENTE', '$FICHA_INTER_ENVIO', '$FICHA_INTER_ENVIO_HORARIO', '$FICHA_INTER_ENVIO_ENDERECO', '$FICHA_INTER_ENVIO_N', '$FICHA_INTER_ENVIO_COMP', '$FICHA_INTER_ENVIO_CEP', '$FICHA_INTER_ENVIO_BAIRRO', '$FICHA_INTER_ENVIO_CIDADE', '$FICHA_INTER_BANCO', '$FICHA_INTER_VEICULO', '$FICHA_INTER_VALOR_FIN', '$FICHA_INTER_VALOR_PARC', '$FICHA_INTER_PAGA', '$FICHA_INTER_ATRASO', '$FICHA_INTER_OBS', '$F_USER_REGISTRO', '$DATA_CADATRO', '$HORA_CADASTRO', '$IP_CADASTRO', '$F_USER_ULT_ALTERACAO', '$DATA_ULT_ALTERACAO', '$HORA_ULT_ALTERACAO', '$IP_ULT_ALTERACAO')");
//if (mysqli_affected_rows ($conexao)>0);
//$val_id_cliente = mysqli_insert_id($conexao);

$sql = "UPDATE tb_ficha_intermediacao SET
FICHA_INTER_USER='$FICHA_INTER_USER',
FICHA_INTER_STATUS='$FICHA_INTER_STATUS',
FICHA_INTER_TIPO='$FICHA_INTER_TIPO',
FICHA_INTER_DATA='$FICHA_INTER_DATA',
FICHA_INTER_CLIENTE='$FICHA_INTER_CLIENTE',
FICHA_INTER_ENVIO='$FICHA_INTER_ENVIO',
FICHA_INTER_ENVIO_HORARIO='$FICHA_INTER_ENVIO_HORARIO',
FICHA_INTER_ENVIO_ENDERECO='$FICHA_INTER_ENVIO_ENDERECO',
FICHA_INTER_ENVIO_N='$FICHA_INTER_ENVIO_N',
FICHA_INTER_ENVIO_COMP='$FICHA_INTER_ENVIO_COMP',
FICHA_INTER_ENVIO_CEP='$FICHA_INTER_ENVIO_CEP',
FICHA_INTER_ENVIO_BAIRRO='$FICHA_INTER_ENVIO_BAIRRO',
FICHA_INTER_ENVIO_CIDADE='$FICHA_INTER_ENVIO_CIDADE',
FICHA_INTER_BUSCA_APREENSAO='$FICHA_INTER_BUSCA_APREENSAO',
FICHA_INTER_BANCO='$FICHA_INTER_BANCO',
FICHA_INTER_VEICULO='$FICHA_INTER_VEICULO',
FICHA_INTER_VALOR_FIN='$FICHA_INTER_VALOR_FIN',
FICHA_INTER_VALOR_PARC='$FICHA_INTER_VALOR_PARC',
FICHA_INTER_PAGA='$FICHA_INTER_PAGA',
FICHA_INTER_ATRASO='$FICHA_INTER_ATRASO',
FICHA_INTER_OBS='$FICHA_INTER_OBS',
F_USER_ULT_ALTERACAO='$F_USER_ULT_ALTERACAO',
DATA_ULT_ALTERACAO='$DATA_ULT_ALTERACAO', 
HORA_ULT_ALTERACAO='$HORA_ULT_ALTERACAO', 
IP_ULT_ALTERACAO='$IP_ULT_ALTERACAO' 
WHERE ID_FICHA_INTER='$ID_FICHA_INTER';";
$res = mysqli_query ($conexao, $sql);

?>
<script language="javascript">
<!-- Caso a condição acima seja verdadeira o script abaiso será execultado-->
//alert ('Dados cadastrado com sucesso!');
location.href = 'operador-ficha-intermediacao.php?ID_LEADS=<?php echo $ID_LEADS; ?>	';
</script>