<?php
//conectando a base de dados...
include "Connections/conecta_banco.php";

//Pegando os valores digitados no formulario de cadastro de clientes e armazenando em arrays super globais
$ID_SUPERVISOR_USER 				= isset($_POST['ID_SUPERVISOR_USER']) ? $_POST['ID_SUPERVISOR_USER'] : '';

$SUPERVISOR_USER_USER		 	= isset($_POST['SUPERVISOR_USER_USER']) ? $_POST['SUPERVISOR_USER_USER'] : '';
$SUPERVISOR_USER_STATUS 			= isset($_POST['SUPERVISOR_USER_STATUS']) ? $_POST['SUPERVISOR_USER_STATUS'] : '';
$SUPERVISOR_USER_TIPO 			= isset($_POST['SUPERVISOR_USER_TIPO']) ? $_POST['SUPERVISOR_USER_TIPO'] : '';
$SUPERVISOR_USER_SUPERVISOR		= isset($_POST['SUPERVISOR_USER_SUPERVISOR']) ? $_POST['SUPERVISOR_USER_SUPERVISOR'] : '';
$SUPERVISOR_USER_OPERADOR 			= isset($_POST['SUPERVISOR_USER_OPERADOR']) ? $_POST['SUPERVISOR_USER_OPERADOR'] : '';
$SUPERVISOR_USER_EQUIPE 			= isset($_POST['SUPERVISOR_USER_EQUIPE']) ? $_POST['SUPERVISOR_USER_EQUIPE'] : '';

$SUPERVISOR_USER_OBS 				= isset($_POST['SUPERVISOR_USER_OBS']) ? $_POST['SUPERVISOR_USER_OBS'] : '';

$F_USER_REGISTRO = $_POST['F_USER_REGISTRO'];
$DATA_CADATRO = date("d/m/Y");
$HORA_CADASTRO = date("H:i");
$IP_CADASTRO = $_SERVER['REMOTE_ADDR'];

//$F_USER_REGISTRO = $_POST['F_USER_REGISTRO'];
//$DATA_CADATRO = date("d/m/Y");
//$HORA_CADASTRO = date("H:i");
//$IP_CADASTRO = $_SERVER['REMOTE_ADDR'];

$F_USER_ULT_ALTERACAO = $_POST['F_USER_REGISTRO'];
$DATA_ULT_ALTERACAO = date("d/m/Y");
$HORA_ULT_ALTERACAO = date("H:i");
$IP_ULT_ALTERACAO = $_SERVER['REMOTE_ADDR'];



//inserindo informoçoes na base...
$sql = "UPDATE tb_supervisor_user SET
SUPERVISOR_USER_USER='$SUPERVISOR_USER_USER',
SUPERVISOR_USER_STATUS='$SUPERVISOR_USER_STATUS',
SUPERVISOR_USER_SUPERVISOR='$SUPERVISOR_USER_SUPERVISOR',
SUPERVISOR_USER_OPERADOR='$SUPERVISOR_USER_OPERADOR',
SUPERVISOR_USER_EQUIPE='$SUPERVISOR_USER_EQUIPE',
SUPERVISOR_USER_OBS='$SUPERVISOR_USER_OBS',
F_USER_ULT_ALTERACAO='$F_USER_ULT_ALTERACAO',
DATA_ULT_ALTERACAO='$DATA_ULT_ALTERACAO', 
HORA_ULT_ALTERACAO='$HORA_ULT_ALTERACAO', 
IP_ULT_ALTERACAO='$IP_ULT_ALTERACAO' 
WHERE ID_SUPERVISOR_USER='$ID_SUPERVISOR_USER';";
$res = mysqli_query ($conexao, $sql);

?>
<script language="javascript">
<!-- Caso a condição acima seja verdadeira o script abaiso será execultado-->
//alert ('Dados cadastrado com sucesso!');
location.href = 'supervisor-user.php?ID_ADMINISTRADOR=<?php echo $SUPERVISOR_USER_SUPERVISOR; ?>';
</script>