<?php
//conectando a base de dados...
include "Connections/conecta_banco.php";

//Pegando os valores digitados no formulario de cadastro de clientes e armazenando em arrays super globais
$ID_ADMINISTRADOR 				= isset($_POST['ID_ADMINISTRADOR']) ? $_POST['ID_ADMINISTRADOR'] : '';

$ADMINISTRADOR_STATUS		 	= isset($_POST['ADMINISTRADOR_STATUS']) ? $_POST['ADMINISTRADOR_STATUS'] : '';
$ADMINISTRADOR_TIPO 			= isset($_POST['ADMINISTRADOR_TIPO']) ? $_POST['ADMINISTRADOR_TIPO'] : '';
$ADMINISTRADOR_DEPARTAMENTO 	= isset($_POST['ADMINISTRADOR_DEPARTAMENTO']) ? $_POST['ADMINISTRADOR_DEPARTAMENTO'] : '';
$ADMINISTRADOR_NOME 			= isset($_POST['ADMINISTRADOR_NOME']) ? $_POST['ADMINISTRADOR_NOME'] : '';
$ADMINISTRADOR_EMAIL 			= isset($_POST['ADMINISTRADOR_EMAIL']) ? $_POST['ADMINISTRADOR_EMAIL'] : '';
$ADMINISTRADOR_SENHA 			= isset($_POST['ADMINISTRADOR_SENHA']) ? $_POST['ADMINISTRADOR_SENHA'] : '';
$ADMINISTRADOR_SENHA = md5($ADMINISTRADOR_SENHA);

$ADMINISTRADOR_FOTO				= isset($_POST['ADMINISTRADOR_FOTO']) ? $_POST['ADMINISTRADOR_FOTO'] : '';
$ADMINISTRADOR_OBS 				= isset($_POST['ADMINISTRADOR_OBS']) ? $_POST['ADMINISTRADOR_OBS'] : '';

//$F_USER_REGISTRO = $_POST['F_USER_REGISTRO'];
//$DATA_CADATRO = date("d/m/Y");
//$HORA_CADASTRO = date("H:i");
//$IP_CADASTRO = $_SERVER['REMOTE_ADDR'];

$F_USER_ULT_ALTERACAO = $_POST['F_USER_REGISTRO'];
$DATA_ULT_ALTERACAO = date("d/m/Y");
$HORA_ULT_ALTERACAO = date("H:i");
$IP_ULT_ALTERACAO = $_SERVER['REMOTE_ADDR'];



//inserindo informoçoes na base...
$sql = "UPDATE tb_administrador SET

ADMINISTRADOR_STATUS='$ADMINISTRADOR_STATUS',
ADMINISTRADOR_TIPO='$ADMINISTRADOR_TIPO',
ADMINISTRADOR_DEPARTAMENTO='$ADMINISTRADOR_DEPARTAMENTO',
ADMINISTRADOR_NOME='$ADMINISTRADOR_NOME',
ADMINISTRADOR_EMAIL='$ADMINISTRADOR_EMAIL',
ADMINISTRADOR_SENHA='$ADMINISTRADOR_SENHA',
ADMINISTRADOR_FOTO='$ADMINISTRADOR_FOTO',
ADMINISTRADOR_OBS='$ADMINISTRADOR_OBS',
F_USER_ULT_ALTERACAO='$F_USER_ULT_ALTERACAO',
DATA_ULT_ALTERACAO='$DATA_ULT_ALTERACAO', 
HORA_ULT_ALTERACAO='$HORA_ULT_ALTERACAO', 
IP_ULT_ALTERACAO='$IP_ULT_ALTERACAO' 

WHERE ID_ADMINISTRADOR='$ID_ADMINISTRADOR';";

$res = mysqli_query ($conexao, $sql);

?>
<script language="javascript">
<!-- Caso a condição acima seja verdadeira o script abaiso será execultado-->
//alert ('Dados alterado com sucesso!');
location.href = 'principal-user.php';
</script>